# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
    - label: Home
      title: Go to the homepage.
      path: homepage
      class: first
    - label: Queue
      path: queue/
    - label: Batches
      path: batches/
    - label: Songs
      path: songs/
    - label: About
      path: about/
      submenu:
          - label: Contact
            path: contact/
      class: last
